import HautevilleHouse.EmbeddingTheoremsUniversalCategories18b20CanonicalLaneLean.MathlibObjects
import HautevilleHouse.EmbeddingTheoremsUniversalCategories18b20CanonicalLaneLean.MathlibStatement
import HautevilleHouse.EmbeddingTheoremsUniversalCategories18b20CanonicalLaneLean.UniversalCategoryEvidence
import HautevilleHouse.EmbeddingTheoremsUniversalCategories18b20CanonicalLaneLean.EmbeddingProof
import HautevilleHouse.EmbeddingTheoremsUniversalCategories18b20CanonicalLaneLean.AdmissibleClass
import HautevilleHouse.EmbeddingTheoremsUniversalCategories18b20CanonicalLaneLean.BridgeLemmas
import HautevilleHouse.EmbeddingTheoremsUniversalCategories18b20CanonicalLaneLean.GateLemmas
import HautevilleHouse.EmbeddingTheoremsUniversalCategories18b20CanonicalLaneLean.FinalTheorem

namespace HautevilleHouse
namespace EmbeddingTheoremsUniversalCategories18b20CanonicalLaneLean

-- This file aggregates all modules for the package.

end EmbeddingTheoremsUniversalCategories18b20CanonicalLaneLean
end HautevilleHouse